<?php

/**
 * @file
 * Defines an example shipping method for testing and development.
 */


function commerce_oz_auspost_menu() {
  $items = array();

  $items['admin/commerce/config/shipping/methods/auspost/edit'] = array(
    'title' => 'Edit',
    'description' => 'Configure the Australia Post shipping method.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_oz_auspost_settings_form'),
    'access arguments' => array('administer shipping'),
    'file' => 'commerce_oz_auspost.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 0,
  );

  return $items;
}


/**
 * Implements hook_commerce_shipping_method_info().
 */
function commerce_oz_auspost_commerce_shipping_method_info() {
  $shipping_methods = array();

  $shipping_methods['auspost_shipping_method'] = array(
    'title' => t('Australia Post'),
    'description' => t('Provides online access to Australia Post services.'),
  );

  return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function commerce_oz_auspost_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['auspost_shipping_method'] = array(
    'title' => t('Australia Post'),
    'description' => t('A $20 flat rate service with express delivery available for an additional $15.'),
    'display_title' => t('Shipping'),
    'shipping_method' => 'Australia Post',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'commerce_oz_auspost_service_rate',
      'details_form' => 'commerce_oz_auspost_service_details_form',
      'details_form_validate' => 'commerce_oz_auspost_service_details_form_validate',
      'details_form_submit' => 'commerce_oz_auspost_service_details_form_submit',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function commerce_oz_auspost_service_rate($shipping_service, $order) {
  return array(
    'amount' => 2000,
    'currency_code' => 'USD',
    'data' => array(),
  );
}

/**
 * Shipping service callback: returns the example shipping service details form.
 */
function commerce_oz_auspost_service_details_form($pane_form, $pane_values, $checkout_pane, $order, $shipping_service) {
  $form = array();

  $pane_values['service_details'] += array(
    'name' => '',
    'express' => '',
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#description' => t('This is a demonstration field coded to fail validation for single character values.'),
    '#default_value' => $pane_values['service_details']['name'],
    '#required' => TRUE,
  );

  $form['express'] = array(
    '#type' => 'checkbox',
    '#title' => t('Express delivery'),
    '#description' => t('Express delivery (costs an additional $15)'),
    '#default_value' => $pane_values['service_details']['express'],
  );

  return $form;
}

/**
 * Shipping service callback: validates the example shipping service details.
 */
function commerce_oz_auspost_service_details_form_validate($details_form, $details_values, $shipping_service, $order, $form_parents) {
  if (strlen($details_values['name']) < 2) {
    form_set_error(implode('][', array_merge($form_parents, array('name'))), t('You must enter a name two or more characters long.'));

    // Even though the form error is enough to stop the submission of the form,
    // it's not enough to stop it from a Commerce standpoint because of the
    // combined validation / submission going on per-pane in the checkout form.
    return FALSE;
  }
}

/**
 * Shipping service callback: increases the shipping line item's unit price if
 * express delivery was selected.
 */
function commerce_oz_auspost_service_details_form_submit($details_form, $details_values, $line_item) {
  if ($details_values['express']) {
    $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

    // Build a price array for the express delivery fee.
    $express_price = array(
      'amount' => 1500,
      'currency_code' => 'USD',
      'data' => array(),
    );

    // Add the express upcharge to the line item unit price.
    $line_item_wrapper->commerce_unit_price->amount = $line_item_wrapper->commerce_unit_price->amount->value() + 1500;

    // Add the express delivery fee component to the unit price.
    $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
      $line_item_wrapper->commerce_unit_price->value(),
      'example_shipping_service_express',
      $express_price,
      TRUE,
      FALSE
    );
  }
}

/**
 * Implements hook_commerce_price_component_type_info().
 */
function commerce_oz_auspost_commerce_price_component_type_info() {
  return array(
    'example_shipping_service_express' => array(
      'title' => t('Express delivery'),
      'weight' => 20,
    ),
  );
}
