<?php

/**
 * @file
 * Implements CommWeb Virtual Payment Service for use in Drupal Commerce.
 */





/**
 * Implements hook_menu().
 */
function commerce_oz_refund_menu() {

 $items['admin/commerce/orders/commweb/commweb-refund-transactions'] = array(

    'title' => t('Refunds'),
    'description' => t('CommWeb Refund Manager'),
    'page callback' => 'commerce_oz_refund_get_transaction_view',
		'access callback' => 'user_access',
    'access arguments' => array('administer commerce_commweb'),
    'type' => MENU_LOCAL_TASK,

  );


 $items['admin/commerce/orders/commweb/commweb-refund-transactions-refunded'] = array(

    'title' => t('Refund Transactions'),
    'description' => t('Transactions created by Refunds'),
    'page callback' => 'commerce_oz_refund_get_refunded_transactions_view',
		'access callback' => 'user_access',
    'access arguments' => array('administer commerce_commweb'),
    'type' => MENU_LOCAL_TASK,

  );
	
	
	// Conextual Link for Refunds
 $items['admin/commerce/orders/%commerce_order/payment/%commerce_payment_transaction/refund'] = array(

    'title' => t('Refund'),
    'page callback' => 'commerce_oz_refund_transaction_test',
   	'page arguments' => array(3, 5),
		'access callback' => true,
    'access arguments' => array('administer commerce_commweb'),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'weight' => 20,
  );

	// http://www.devel.lawnsale.com.au/admin/commerce/orders/603/payment/796/delete


  return $items;
}

function commerce_oz_refund_transaction_test($order, $transaction) 
{
//	// dsm($order, 'Order');
//	// dsm($transaction, 'Transaction');
	commerce_oz_refund_transaction_action($transaction, $context) ;
	drupal_goto('admin/commerce/orders/' . $order->order_id . '/payment');
}

/**
 * Implements hook_menu_contextual_links_alter().
 *
 * Remove the reverse link from the transaction operations if the transaction
 * can not be reversed.
 */
function commerce_oz_refund_menu_contextual_links_alter(&$links, $router_item, $root_path) {
  if (isset($links['commerce-commweb-transaction-refund'])) {
    if (!commerce_oz_refund_transaction_refundable($router_item['page_arguments'][1])) {
      unset($links['commerce-commweb-transaction-refund']);
    }
  }
}
/**
 * Return true if refundable.
 */
function commerce_oz_refund_transaction_refundable($transaction)
{
	// dsm($transaction, 'refundable');
	
	return (
    $transaction->payment_method == 'commerce_commweb'
  //  && isset($transaction->payload['refunded'])
    && $transaction->status == COMMERCE_PAYMENT_STATUS_SUCCESS
  );
}

/**
 * Implements hook_action_info().
 */
function commerce_oz_refund_action_info() {
  return array(
  
    'commerce_oz_refund_transaction_action' => array(
      'type' => 'system',
      'label' => t('Refund Transaction'),
      'configurable' => FALSE,
      'hooks' => array('any' => TRUE),
      'triggers' => array('any'),
      ),
  );
}

/**
 * Implements hook_views_api().
 */
function commerce_oz_refund_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_oz_refund') . '/includes/views',
  );
}


function commerce_oz_refund_get_transaction_view() {
    $viewname = 'commweb_refund_transactions'; // use the machine name of the view
    $viewdisplay = 'page'; // use the machine readable name of the display or 'default'
    return views_embed_view($viewname, $viewdisplay);
}

function commerce_oz_refund_get_refunded_transactions_view() {
    $viewname = 'commweb_refund_transactions'; // use the machine name of the view
    $viewdisplay = 'page_1'; // use the machine readable name of the display or 'default'
    return views_embed_view($viewname, $viewdisplay);
}


function commerce_oz_refund_transaction_action_form($context) {

	// // dsm($context);

	$form = array();
  
   /* Provide a textfield of to pass different Amounts to MIGS */
 $form['amount'] = array(
     '#input' => TRUE,

    '#type' => 'textfield',
    '#size' => 6,
    '#maxlength' => 10,
   		
      '#title' => t('Refund Amount'), 
      '#default_value' => $order->commerce_order_total['und'][0]['amount'],
      '#disabled'  => FALSE,
      '#description' => t('Update the Amount (in cents) to refund.'),
      '#required' => FALSE, 
    );  

  
  return $form;
  
  }



/**
 * Validates settings form for action_example_node_sticky_action().
 * Verifies that user exists before continuing.
 */
function commerce_oz_refund_transaction_action_validate($form, $form_state) {
  
  // No validation
}

/**
 * Submit handler for action_example_node_sticky_action.
 *
 * Returns an associative array of values which will be available in the
 * $context when an action is executed.
 */
function commerce_oz_refund_transaction_action_submit($form, $form_state) {
  return array('lawnsale' => $form_state['values']['lawnsale']);
}



/**
 *
 * @param $node
 *   A node object provided by the associated trigger.
 * @param $context
 *   Array with the following elements:
 *   - 'author': username of the author's content this function will promote and
 *     set as sticky.
 */
function commerce_oz_refund_transaction_action($node, $context) 
{
  
		if (function_exists('// dsm')) {
			// dsm($node, 'Transaction $node');
		}
		
		// Write a Transaction record
		$transaction = commerce_payment_transaction_new('commerce_commweb', $node->order_id);
		
		// Save the transaction information.
		commerce_payment_transaction_save($transaction);
		
		$merchTxnRef = $node->payload['request']['vpc_MerchTxnRef'];
		$amount = $node->payload['request']['vpc_Amount'];
		$trans_no = $node->payload['response']['vpc_TransactionNo'];
		$order_id = $node->order_id;
		
		$refund_request_string = _build_vpc_refund_payload($merchTxnRef, $amount, $trans_no);
		$request_map = _process_vpc_refund_request($refund_request_string);
		
		$response_string = _post_vpc_refund_request($refund_request_string);
		$response_map = _process_vpc_refund_response($transaction, $response_string, $request_map, $order_id, $node->transaction_id);
		
	//	// dsm($node, 'Transaction $node');

		
		// Save the transaction information.
		commerce_payment_transaction_save($transaction);
		
		_update_source_transaction($node, $transaction);
		
		rules_invoke_event('commerce_oz_refund_complete', $transaction);

}


function _build_vpc_refund_payload($merchTxnRef, $amount, $trans_no) 

{
		
		// Get the API Credentials
		
		$settings = _commweb_get_var('commerce_oz_gateway_cba');
		
		$merchantid = $settings['merchant_id'];
		$accesscode = $settings['access_code'];
		$user = $settings['refund_username'];
		$password = $settings['refund_password'];
		
		$postData = '';
		$amp = '&';
		
		$postData .= 'vpc_Version' . '=' . COMMERCE_COMMWEB_vpc_Version . $amp;
		$postData .= 'vpc_Command' . '=' . 'refund' . $amp;
		$postData .= 'vpc_MerchTxnRef' . '=' . $merchTxnRef . $amp;
		$postData .= 'vpc_AccessCode' . '=' . $accesscode . $amp;
		$postData .= 'vpc_Merchant' . '=' . $merchantid . $amp; 
		$postData .= 'vpc_TransNo' . '=' . $trans_no . $amp;
		$postData .= 'vpc_Amount' . '=' . $amount . $amp;
		$postData .= 'vpc_User' . '=' . $user . $amp;
		$postData .= 'vpc_Password' . '=' . $password;
		
		return $postData;
}


function _post_vpc_refund_request($post_data)
{
	ob_start();
	
	// initialise
	$curlhandle = curl_init();
	
	// set the URL of the VPC
	curl_setopt ($curlhandle, CURLOPT_URL, COMMERCE_COMMWEB_URL);
	curl_setopt ($curlhandle, CURLOPT_POST, 1);
	curl_setopt ($curlhandle, CURLOPT_POSTFIELDS, $post_data);
	curl_setopt ($curlhandle, CURLOPT_SSL_VERIFYPEER, 0);
	curl_setopt ($curlhandle, CURLOPT_SSL_VERIFYHOST, 0);
	
	// connect
	curl_exec ($curlhandle);
	
	// get response
	$response = ob_get_contents();
	
	// turn output buffering off.
	ob_end_clean();
	
	return $response;

}



function _process_vpc_refund_request($request_string)
{
		
		module_load_include('inc', 'commerce_oz', 'commerce_oz_migs_2p');
	  $request_map = array();
		parse_str($request_string, $request_map);
		$request_map['vpc_Merchant'] = _commweb_build_merchant_string($request_map['vpc_Merchant']);
		$request_map['vpc_AccessCode'] = _commweb_build_accesscode_string($request_map['vpc_AccessCode']);
		$request_map['vpc_Password'] = _commweb_build_refund_user_password_string($request_map['vpc_Password']);
		$request_map['vpc_User'] = _commweb_build_refund_user_string($request_map['vpc_User']);
		return $request_map;
}


function _process_vpc_refund_response($transaction, $response_string, $request_map, $order_id = 0, $old_trans_id = 0, $test_message = '')
{
	// Map VPC repsonse to array
	$response_map = array();
	parse_str($response_string, $response_map);
	$response_map['vpc_Merchant'] = _commweb_build_merchant_string($response_map['vpc_Merchant']);
	
	// Update the transaction object
  $transaction->instance_id = 'commerce_commweb|commerce_payment_commerce_commweb';
  $transaction->amount = $response_map['vpc_Amount'];
  $transaction->currency_code = 'AUD';
  $transaction->payload = array('request' => $request_map, 
  															'response' => $response_map
  															);
  
  $transaction->remote_id = $response_map['vpc_TransactionNo'];    
  $transaction->remote_status = $response_map['vpc_TxnResponseCode'];  
  
  $transaction->status = $response_map['vpc_TxnResponseCode'] ? COMMERCE_PAYMENT_STATUS_FAILURE : COMMERCE_PAYMENT_STATUS_SUCCESS;
  
  $transaction->message = $test_message . '<strong>Refund</strong> Code: @code - @message <br />Order ID: <a href="/admin/commerce/orders/@order_id">@order_id</a> <br />Refunded Transaction: <a href="/admin/commerce/orders/@order_id/payment/@trans_id/view">@trans_id</a>'; 
  
  $transaction->message_variables = array(
  	'@code' => $response_map['vpc_TxnResponseCode'],
  	'@message' => $response_map['vpc_Message'],
  	'@trans_id' => $old_trans_id,
  	'@order_id' => $order_id,
  		);
  
  return $response_map;		
  		
}

function _update_source_transaction($transaction, $refund_transaction)
{
	
	// Update the source transaction object message
  
  $transaction->message = $transaction->message . '<br />Refunded Code: @code - @message 
  <br />Refund Transaction: <b>@refund_trans_id</b>'; 
  
  $transaction->message_variables = $transaction->message_variables + array(
  	'@refund_trans_id' => $refund_transaction->transaction_id,
  	'@order_id' => $transaction->order_id,
  		);
  
    $transaction->payload = array('request' => $transaction->payload['request'], 
  															'response' => $transaction->payload['response'],
  															'refunded' => $refund_transaction->payload['response'],
  															);
  
  commerce_payment_transaction_save($transaction);
  
 // // dsm($transaction, 'Source Transaction');
 // // dsm($refund_transaction, 'Refund Transaction');
  		
}

function commerce_oz_refund_update_source_transaction($transaction, $refund_transaction)
{
	
	// Update the source transaction object message
  
  $transaction->message = $transaction->message . '<br />Refunded Code: @code - @message 
  <br />Refund Transaction: <b>@refund_trans_id</b>'; 
  
  $transaction->message_variables = $transaction->message_variables + array(
  	'@refund_trans_id' => $refund_transaction->transaction_id,
  	'@order_id' => $transaction->order_id,
  		);
  
    $transaction->payload = array('request' => $transaction->payload['request'], 
  															'response' => $transaction->payload['response'],
  															'refunded' => $refund_transaction->payload['response'],
  															);
  
  commerce_payment_transaction_save($transaction);
  
 // // dsm($transaction, 'Source Transaction');
 // // dsm($refund_transaction, 'Refund Transaction');
  		
}


